---
title: jmml
timezone: Europe/Madrid
collections:
  posts:
    title: Posts
    output: true
    layout: post
  posts_ugr:
    title: Posts Ugr
    output: true
  uploads:
    title: Uploads
    output: true
email:
description: Página web personal de José María Martín Luque.
baseurl:
url: http://yourdomain.com
twitter_username: jmml97
github_username: jmml97
markdown: kramdown
defaults:
  -
  scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "José María"
  -
