---
title: jmml
timezone: Europe/Madrid
collections:
  posts:
    title: Posts
    output: true
    layout: post
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: José María
email: 
description: Página web personal de José María Martín Luque.
baseurl: 
url: http://yourdomain.com
twitter_username: jmml97
github_username: jmml97
markdown: kramdown
